[lint]
ignore = [
    "B008",
    "RUF012",
    "UP035",
    "F401",
    "ASYNC230", # Разрешаем обычный open() для чтения ключа
    "S110",     # Разрешаем использовать pass в блоке except
]
